package claude

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeAgents(t *testing.T, dir, body string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, SourceFile), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestMirror_CreatesMissingClaudeMD(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# root\nbody\n")

	res, err := Mirror(Options{RootDir: root})
	if err != nil {
		t.Fatalf("Mirror: %v", err)
	}
	if len(res.Created) != 1 {
		t.Fatalf("expected 1 created, got %+v", res)
	}
	got, err := os.ReadFile(filepath.Join(root, TargetFile))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(got), AutoGenMarker) {
		t.Errorf("mirror missing autogen marker: %q", string(got))
	}
	if !strings.Contains(string(got), "# root\nbody") {
		t.Errorf("mirror missing source body: %q", string(got))
	}
}

func TestMirror_UpdatesAutogeneratedClaudeMD(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# v1\n")

	// First run creates.
	if _, err := Mirror(Options{RootDir: root}); err != nil {
		t.Fatal(err)
	}
	// Change source. Second run should update.
	writeAgents(t, root, "# v2\n")
	res, err := Mirror(Options{RootDir: root})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Updated) != 1 {
		t.Errorf("expected 1 updated, got %+v", res)
	}
	got, _ := os.ReadFile(filepath.Join(root, TargetFile))
	if !strings.Contains(string(got), "# v2") {
		t.Errorf("update did not propagate: %q", got)
	}
}

func TestMirror_SkipsUserCustomizedClaudeMD(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# agents\n")
	// Pre-existing v1 / hand-written CLAUDE.md without the marker.
	custom := "# hand-written\nstay\n"
	if err := os.WriteFile(filepath.Join(root, TargetFile), []byte(custom), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := Mirror(Options{RootDir: root})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Skipped) != 1 {
		t.Errorf("expected 1 skipped, got %+v", res)
	}
	got, _ := os.ReadFile(filepath.Join(root, TargetFile))
	if string(got) != custom {
		t.Errorf("user-customized file was modified: %q", got)
	}
}

func TestMirror_ForceOverwritesUserCustomized(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# agents\n")
	if err := os.WriteFile(filepath.Join(root, TargetFile), []byte("# hand-written\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := Mirror(Options{RootDir: root, Force: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Updated) != 1 {
		t.Errorf("expected 1 updated under Force, got %+v", res)
	}
	got, _ := os.ReadFile(filepath.Join(root, TargetFile))
	if !strings.HasPrefix(string(got), AutoGenMarker) {
		t.Errorf("force did not install marker: %q", got)
	}
}

func TestMirror_DryRunDoesNotWrite(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# agents\n")

	res, err := Mirror(Options{RootDir: root, DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 1 {
		t.Errorf("expected 1 reported create, got %+v", res)
	}
	if _, err := os.Stat(filepath.Join(root, TargetFile)); !os.IsNotExist(err) {
		t.Errorf("dry-run wrote file: err=%v", err)
	}
}

func TestMirror_WalksSubdirsAndSkipsVCS(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# root\n")
	writeAgents(t, filepath.Join(root, "sub"), "# sub\n")
	// .git dir with an AGENTS.md should be skipped (hidden + skip set).
	writeAgents(t, filepath.Join(root, ".git"), "# git\n")
	// node_modules should be skipped by the embedded skipDirSet.
	writeAgents(t, filepath.Join(root, "node_modules", "x"), "# nm\n")

	res, err := Mirror(Options{RootDir: root, MaxDepth: -1})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 2 {
		t.Fatalf("expected 2 mirrors (root + sub), got %d: %+v", len(res.Created), res.Created)
	}
	if _, err := os.Stat(filepath.Join(root, ".git", TargetFile)); !os.IsNotExist(err) {
		t.Errorf(".git CLAUDE.md should not exist")
	}
	if _, err := os.Stat(filepath.Join(root, "node_modules", "x", TargetFile)); !os.IsNotExist(err) {
		t.Errorf("node_modules CLAUDE.md should not exist")
	}
}

func TestMirror_IdempotentOnSecondRun(t *testing.T) {
	root := t.TempDir()
	writeAgents(t, root, "# agents\n")

	if _, err := Mirror(Options{RootDir: root}); err != nil {
		t.Fatal(err)
	}
	res, err := Mirror(Options{RootDir: root})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created) != 0 || len(res.Updated) != 0 {
		t.Errorf("second run should be a no-op, got %+v", res)
	}
}

func TestMirror_IgnoresDirsWithoutAgentsMD(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "empty"), 0o755); err != nil {
		t.Fatal(err)
	}

	res, err := Mirror(Options{RootDir: root})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Created)+len(res.Updated)+len(res.Skipped) != 0 {
		t.Errorf("expected no-op when no AGENTS.md anywhere, got %+v", res)
	}
}
