// Package claude mirrors AGENTS.md files into sibling CLAUDE.md files so
// Claude Code (which still treats CLAUDE.md as primary) picks up the
// same project context that every AGENTS.md-native tool already reads.
//
// Why this lives in core: every other major coding assistant reads
// AGENTS.md natively today. Claude is the lone outlier that needs an
// active translation step, and requiring every Samuel user to install a
// plugin to obtain a CLAUDE.md mirror was friction without payoff. The
// rest of the translator surface — anything richer than a flat mirror,
// any future tool — stays in plugins; only this one
// trivial-but-mandatory mirror is built in.
//
// Behavior matches sync.WriteFolderContext: missing → create,
// autogen-marker → update, user-customized → skip unless Force. Files
// without the marker are treated as v1-authored or hand-edited and are
// preserved.
package claude

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/samuelpkg/samuel/internal/sync"
)

// AutoGenMarker is the substring used to identify CLAUDE.md files this
// translator owns. Distinct from sync.AutoGenMarker so a user can keep a
// hand-written AGENTS.md and still have Samuel manage CLAUDE.md (or vice
// versa) — though in practice the translator only writes CLAUDE.md
// alongside an AGENTS.md it sees.
const AutoGenMarker = "<!-- Auto-generated by Samuel (Claude translator)"

// TargetFile is the per-directory filename this translator writes.
const TargetFile = "CLAUDE.md"

// SourceFile is the per-directory filename this translator reads.
const SourceFile = "AGENTS.md"

// Options configures a Mirror run. Mirrors sync.Options for the fields
// that map directly; the translator does not need MaxDepth-by-itself
// semantics because it only acts on directories that already carry an
// AGENTS.md.
type Options struct {
	// RootDir is the project root to walk.
	RootDir string
	// MaxDepth caps how deep the walker descends. -1 = unlimited.
	MaxDepth int
	// Force overwrites user-customized CLAUDE.md files (no autogen
	// marker present).
	Force bool
	// DryRun reports what would change without writing.
	DryRun bool
	// SkipOverrides extends the dir-skip policy. Reuses sync.Overrides
	// so a single user config drives both walks.
	SkipOverrides sync.Overrides
}

// Result tracks outcomes of a mirror run, mirroring sync.Result so the
// caller can render both in the same format.
type Result struct {
	Created []string
	Updated []string
	Skipped []string
	Errors  []error
}

// Mirror walks RootDir and, for every directory containing an
// AGENTS.md, writes a CLAUDE.md sibling that points readers at AGENTS.md
// as the source of truth and embeds a verbatim copy of its contents.
//
// Mirror is idempotent: running it twice produces no diffs unless the
// underlying AGENTS.md changed.
func Mirror(opts Options) (*Result, error) {
	result := &Result{}
	rootInfo, err := os.Stat(opts.RootDir)
	if err != nil {
		return nil, fmt.Errorf("cannot access root directory: %w", err)
	}
	if !rootInfo.IsDir() {
		return nil, fmt.Errorf("not a directory: %s", opts.RootDir)
	}

	walkErr := filepath.WalkDir(opts.RootDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return nil
		}
		if !d.IsDir() {
			return nil
		}
		// The translator runs at the same depths sync does.
		if path != opts.RootDir {
			name := d.Name()
			if sync.ShouldSkipDir(name, opts.SkipOverrides) {
				return filepath.SkipDir
			}
			if opts.MaxDepth >= 0 {
				rel, relErr := filepath.Rel(opts.RootDir, path)
				if relErr != nil {
					result.Errors = append(result.Errors, fmt.Errorf("%s: rel path: %w", path, relErr))
					return filepath.SkipDir
				}
				depth := walkDepth(rel)
				if depth > opts.MaxDepth {
					return filepath.SkipDir
				}
			}
		}
		// Only mirror dirs that carry an AGENTS.md.
		sourcePath := filepath.Join(path, SourceFile)
		body, readErr := os.ReadFile(sourcePath)
		if readErr != nil {
			return nil
		}
		writeMirror(path, body, opts, result)
		return nil
	})

	return result, walkErr
}

// writeMirror commits one CLAUDE.md mirror, honoring the autogen marker
// contract so user-customized files are preserved.
func writeMirror(dir string, source []byte, opts Options, result *Result) {
	targetPath := filepath.Join(dir, TargetFile)
	content := renderMirror(source)

	existing, err := os.ReadFile(targetPath)
	if err != nil {
		if !opts.DryRun {
			if writeErr := os.WriteFile(targetPath, []byte(content), 0o644); writeErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("write %s: %w", targetPath, writeErr))
				return
			}
		}
		result.Created = append(result.Created, targetPath)
		return
	}
	if IsAutoGenerated(string(existing)) {
		if string(existing) == content {
			return
		}
		if !opts.DryRun {
			if writeErr := os.WriteFile(targetPath, []byte(content), 0o644); writeErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("write %s: %w", targetPath, writeErr))
				return
			}
		}
		result.Updated = append(result.Updated, targetPath)
		return
	}
	if opts.Force {
		if !opts.DryRun {
			if writeErr := os.WriteFile(targetPath, []byte(content), 0o644); writeErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("write %s: %w", targetPath, writeErr))
				return
			}
		}
		result.Updated = append(result.Updated, targetPath)
		return
	}
	result.Skipped = append(result.Skipped, targetPath)
}

// renderMirror builds the CLAUDE.md body. The marker comes first so
// IsAutoGenerated can detect it without parsing the whole file.
func renderMirror(source []byte) string {
	return AutoGenMarker + ". Source: " + SourceFile + ". -->\n" +
		"<!-- Edit " + SourceFile + " and run `samuel sync` to refresh this file. -->\n\n" +
		string(source)
}

// IsAutoGenerated reports whether content carries the translator's
// autogen marker.
func IsAutoGenerated(content string) bool {
	return strings.Contains(content, AutoGenMarker)
}

func walkDepth(rel string) int {
	if rel == "." || rel == "" {
		return 0
	}
	return len(strings.Split(rel, string(filepath.Separator)))
}
