// Package sync writes per-folder AGENTS.md files describing each
// directory's purpose, primary languages, key files, and whether tests
// live there. Ported from samuel_v1/internal/core/sync.go with two
// invariants tightened:
//
//  1. AGENTS.md only. v1 emitted tool-specific context files alongside
//     AGENTS.md; v2 is agent-agnostic (RFD 0009) — the framework writes
//     the vendor-neutral AGENTS.md exclusively. Tool-specific files
//     come from translator plugins, not the core.
//
//  2. Defaults are embedded; users override via samuel.toml [sync.*].
//     The defaults still ship in this package so the framework is
//     usable before the user has authored any sync overrides.
//
// Hook stubs (sync.before / analyze-folder / write-agents-md / after)
// live in hooks.go. Bodies arrive with PRD 0004.
package sync

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// AutoGenMarker is the substring used to identify auto-generated
// AGENTS.md files. Files without this marker are treated as
// user-customized and skipped unless Options.Force is true.
const AutoGenMarker = "<!-- Auto-generated by Samuel"

// FolderAnalysis holds the analysis results for a single directory.
type FolderAnalysis struct {
	Path      string
	Name      string
	Languages map[string]int // language name → file count
	Purpose   string
	KeyFiles  []string
	HasTests  bool
	FileCount int
}

// Options configures a sync run.
type Options struct {
	// RootDir is the project root to walk.
	RootDir string
	// MaxDepth caps how deep the walker descends. -1 = unlimited.
	MaxDepth int
	// Force overwrites user-customized AGENTS.md files (no autogen
	// marker present).
	Force bool
	// DryRun reports what would change without writing.
	DryRun bool

	// Overrides extend or replace the built-in maps. A nil Overrides
	// (or a partially-populated one) falls back to the embedded
	// defaults below.
	Overrides Overrides
}

// Overrides is the user-driven extension of the embedded heuristic
// maps. Loaded from samuel.toml [sync.*] sections.
type Overrides struct {
	// Languages maps file extensions to language names. Entries here
	// override the built-in ExtensionLanguageMap on equal keys.
	Languages map[string]string
	// Folders maps folder names to inferred purposes.
	Folders map[string]string
	// KeyFiles maps well-known filenames to short descriptions.
	KeyFiles map[string]string
	// Skip extends the set of directory names to skip (in addition to
	// hidden dirs and the embedded skipDirSet).
	Skip []string
}

// Result tracks outcomes of the sync operation.
type Result struct {
	Created []string
	Updated []string
	Skipped []string
	Errors  []error
}

// SyncFolderContext walks RootDir and writes per-folder AGENTS.md
// files. It is the v2 replacement for v1's SyncFolderCLAUDEMDs.
//
// Hooks fire at the boundaries listed in hooks.go. With no methodology
// installed, the hooks are no-ops.
func SyncFolderContext(opts Options) (*Result, error) {
	result := &Result{}
	rootInfo, err := os.Stat(opts.RootDir)
	if err != nil {
		return nil, fmt.Errorf("cannot access root directory: %w", err)
	}
	if !rootInfo.IsDir() {
		return nil, fmt.Errorf("not a directory: %s", opts.RootDir)
	}

	hooks := defaultHooks()
	hooks.Before(opts)

	walkErr := filepath.WalkDir(opts.RootDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return nil // skip inaccessible dirs
		}
		if !d.IsDir() {
			return nil
		}
		if path == opts.RootDir {
			return nil
		}
		name := d.Name()
		if ShouldSkipDir(name, opts.Overrides) {
			return filepath.SkipDir
		}
		if opts.MaxDepth >= 0 {
			rel, relErr := filepath.Rel(opts.RootDir, path)
			if relErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("%s: rel path: %w", path, relErr))
				return filepath.SkipDir
			}
			depth := len(strings.Split(rel, string(filepath.Separator)))
			if depth > opts.MaxDepth {
				return filepath.SkipDir
			}
		}

		analysis, err := AnalyzeFolder(path, opts.Overrides)
		if err != nil {
			result.Errors = append(result.Errors, fmt.Errorf("%s: %w", path, err))
			return nil
		}
		hooks.AnalyzeFolder(analysis)

		content := GenerateContent(analysis)
		hooks.WriteAgentsMD(analysis, &content)

		WriteFolderContext(path, content, opts, result)
		return nil
	})

	hooks.After(result)
	return result, walkErr
}

// WriteFolderContext writes AGENTS.md (only) to dir. It enforces the
// AGENTS.md-only invariant — no tool-specific context files are
// emitted.
//
// Behavior matrix:
//
//	missing file       -> create
//	autogen marker     -> update
//	user-customized    -> skip unless opts.Force
func WriteFolderContext(dir, content string, opts Options, result *Result) {
	filePath := filepath.Join(dir, "AGENTS.md")
	existing, err := os.ReadFile(filePath)
	if err != nil {
		if !opts.DryRun {
			if writeErr := os.WriteFile(filePath, []byte(content), 0o644); writeErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("write %s: %w", filePath, writeErr))
				return
			}
		}
		result.Created = append(result.Created, filePath)
		return
	}
	if IsAutoGenerated(string(existing)) {
		if !opts.DryRun {
			if writeErr := os.WriteFile(filePath, []byte(content), 0o644); writeErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("write %s: %w", filePath, writeErr))
				return
			}
		}
		result.Updated = append(result.Updated, filePath)
		return
	}
	if opts.Force {
		if !opts.DryRun {
			if writeErr := os.WriteFile(filePath, []byte(content), 0o644); writeErr != nil {
				result.Errors = append(result.Errors, fmt.Errorf("write %s: %w", filePath, writeErr))
				return
			}
		}
		result.Updated = append(result.Updated, filePath)
		return
	}
	result.Skipped = append(result.Skipped, filePath)
}

// AnalyzeFolder reads dirPath and classifies its contents. Overrides
// extend the embedded maps on a per-entry basis (an override entry for
// a known key WINS; entries for unknown keys are added to the set).
func AnalyzeFolder(dirPath string, ov Overrides) (*FolderAnalysis, error) {
	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil, err
	}
	a := &FolderAnalysis{
		Path:      dirPath,
		Name:      filepath.Base(dirPath),
		Languages: make(map[string]int),
	}
	languages := mergedLanguages(ov)
	keyFiles := mergedKeyFiles(ov)
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		ext := strings.ToLower(filepath.Ext(name))
		if lang, ok := languages[ext]; ok {
			a.Languages[lang]++
			a.FileCount++
		}
		if isTestFile(name) {
			a.HasTests = true
		}
		if desc, ok := keyFiles[name]; ok {
			a.KeyFiles = append(a.KeyFiles, fmt.Sprintf("`%s` — %s", name, desc))
		}
	}
	a.Purpose = inferPurpose(a.Name, ov)
	sort.Strings(a.KeyFiles)
	return a, nil
}

// GenerateContent renders an AGENTS.md body from a folder analysis. The
// first line is the autogen marker, which IsAutoGenerated keys on.
func GenerateContent(a *FolderAnalysis) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s\n\n", a.Name))
	b.WriteString(fmt.Sprintf("%s. Customize with folder-specific instructions. -->\n", AutoGenMarker))
	b.WriteString("<!-- AI agents load this file when working in this directory. -->\n")

	b.WriteString("\n## Purpose\n\n")
	b.WriteString(a.Purpose)
	b.WriteString("\n")

	if len(a.Languages) > 0 {
		b.WriteString("\n## Languages\n\n")
		for _, e := range sortedLanguages(a.Languages) {
			b.WriteString(fmt.Sprintf("- %s (%d files)\n", e.name, e.count))
		}
	}
	if len(a.KeyFiles) > 0 {
		b.WriteString("\n## Key Files\n\n")
		for _, kf := range a.KeyFiles {
			b.WriteString(fmt.Sprintf("- %s\n", kf))
		}
	}
	if a.HasTests {
		b.WriteString("\n## Testing\n\nThis directory contains test files.\n")
	}
	return b.String()
}

// IsAutoGenerated reports whether content carries the autogen marker.
func IsAutoGenerated(content string) bool {
	return strings.Contains(content, AutoGenMarker)
}

// ShouldSkipDir is the routing point for "don't descend into this dir".
// Hidden dirs always skip; the embedded skip set covers VCS, IDE,
// language build outputs; user overrides extend the set.
//
// Exported so adjacent packages (e.g. translator/claude) can reuse the
// same walk policy without forking the skip rules.
func ShouldSkipDir(name string, ov Overrides) bool {
	if strings.HasPrefix(name, ".") {
		return true
	}
	if skipDirSet[name] {
		return true
	}
	for _, n := range ov.Skip {
		if n == name {
			return true
		}
	}
	return false
}

func isTestFile(name string) bool {
	lower := strings.ToLower(name)
	if strings.HasSuffix(lower, "_test.go") {
		return true
	}
	if strings.HasPrefix(lower, "test_") || strings.HasSuffix(lower, "_test.py") {
		return true
	}
	if strings.Contains(lower, ".test.") || strings.Contains(lower, ".spec.") {
		return true
	}
	return false
}

func inferPurpose(name string, ov Overrides) string {
	if ov.Folders != nil {
		if p, ok := ov.Folders[name]; ok {
			return p
		}
	}
	if p, ok := folderPurposeMap[name]; ok {
		return p
	}
	return "Package directory."
}

func mergedLanguages(ov Overrides) map[string]string {
	if len(ov.Languages) == 0 {
		return extensionLanguageMap
	}
	out := make(map[string]string, len(extensionLanguageMap)+len(ov.Languages))
	for k, v := range extensionLanguageMap {
		out[k] = v
	}
	for k, v := range ov.Languages {
		out[k] = v
	}
	return out
}

func mergedKeyFiles(ov Overrides) map[string]string {
	if len(ov.KeyFiles) == 0 {
		return keyFileDescriptions
	}
	out := make(map[string]string, len(keyFileDescriptions)+len(ov.KeyFiles))
	for k, v := range keyFileDescriptions {
		out[k] = v
	}
	for k, v := range ov.KeyFiles {
		out[k] = v
	}
	return out
}

type langEntry struct {
	name  string
	count int
}

func sortedLanguages(m map[string]int) []langEntry {
	out := make([]langEntry, 0, len(m))
	for n, c := range m {
		out = append(out, langEntry{n, c})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].count != out[j].count {
			return out[i].count > out[j].count
		}
		return out[i].name < out[j].name
	})
	return out
}

// --- Embedded defaults (ported from v1) ---

var extensionLanguageMap = map[string]string{
	".go":    "Go",
	".py":    "Python",
	".ts":    "TypeScript",
	".tsx":   "TypeScript",
	".js":    "JavaScript",
	".jsx":   "JavaScript",
	".rs":    "Rust",
	".java":  "Java",
	".kt":    "Kotlin",
	".kts":   "Kotlin",
	".cs":    "C#",
	".rb":    "Ruby",
	".php":   "PHP",
	".swift": "Swift",
	".dart":  "Dart",
	".lua":   "Lua",
	".r":     "R",
	".R":     "R",
	".c":     "C",
	".h":     "C",
	".cpp":   "C++",
	".hpp":   "C++",
	".cc":    "C++",
	".zig":   "Zig",
	".sol":   "Solidity",
	".cu":    "CUDA",
	".cuh":   "CUDA",
	".sql":   "SQL",
	".sh":    "Shell",
	".bash":  "Shell",
	".zsh":   "Shell",
	".html":  "HTML",
	".css":   "CSS",
	".scss":  "CSS",
	".less":  "CSS",
	".yaml":  "YAML",
	".yml":   "YAML",
	".json":  "JSON",
	".toml":  "TOML",
	".xml":   "XML",
	".md":    "Markdown",
	".proto": "Protobuf",
}

var folderPurposeMap = map[string]string{
	"cmd":        "Application entry points and CLI commands.",
	"internal":   "Private application packages (not importable externally).",
	"pkg":        "Public library packages.",
	"api":        "API definitions, schemas, and handlers.",
	"web":        "Web application assets and handlers.",
	"ui":         "User interface components and helpers.",
	"models":     "Data models and domain entities.",
	"handlers":   "Request handlers and controllers.",
	"middleware": "HTTP/gRPC middleware.",
	"services":   "Business logic and service layer.",
	"repository": "Data access and storage layer.",
	"config":     "Configuration loading and management.",
	"migrations": "Database migration files.",
	"scripts":    "Build, deploy, and utility scripts.",
	"tools":      "Development tools and code generators.",
	"test":       "Test files and test utilities.",
	"tests":      "Test files and test utilities.",
	"testdata":   "Test fixture data.",
	"fixtures":   "Test fixture data.",
	"docs":       "Documentation source files.",
	"doc":        "Documentation source files.",
	"assets":     "Static assets (images, fonts, etc.).",
	"static":     "Static files served directly.",
	"public":     "Publicly accessible files.",
	"templates":  "Template files for rendering.",
	"views":      "View templates and layouts.",
	"components": "Reusable UI components.",
	"pages":      "Page-level components or routes.",
	"routes":     "Route definitions.",
	"lib":        "Shared library code.",
	"utils":      "Utility and helper functions.",
	"helpers":    "Helper functions and utilities.",
	"core":       "Core business logic and domain layer.",
	"domain":     "Domain models and business rules.",
	"adapters":   "External service adapters and integrations.",
	"ports":      "Interface definitions (hexagonal architecture).",
	"infra":      "Infrastructure and deployment configuration.",
	"deploy":     "Deployment scripts and configurations.",
	"github":     "GitHub-specific integrations and API clients.",
	"commands":   "CLI command implementations.",
}

var keyFileDescriptions = map[string]string{
	"main.go":             "Entry point",
	"main.py":             "Entry point",
	"index.ts":            "Entry point",
	"index.js":            "Entry point",
	"app.py":              "Application entry point",
	"app.ts":              "Application entry point",
	"app.go":              "Application entry point",
	"server.go":           "Server setup",
	"server.ts":           "Server setup",
	"package.json":        "Node.js package manifest",
	"go.mod":              "Go module definition",
	"Cargo.toml":          "Rust package manifest",
	"pyproject.toml":      "Python project configuration",
	"Dockerfile":          "Container build definition",
	"Makefile":            "Build configuration",
	"justfile":            "Just command runner",
	"docker-compose.yml":  "Docker Compose services",
	"docker-compose.yaml": "Docker Compose services",
	".env.example":        "Environment variable template",
	"README.md":           "Documentation",
}

var skipDirSet = map[string]bool{
	".git":          true,
	".claude":       true,
	".agent":        true,
	".idea":         true,
	".vscode":       true,
	"node_modules":  true,
	"vendor":        true,
	"__pycache__":   true,
	".venv":         true,
	"venv":          true,
	"env":           true,
	"target":        true,
	"build":         true,
	"dist":          true,
	"out":           true,
	".next":         true,
	".nuxt":         true,
	"coverage":      true,
	".cache":        true,
	".pytest_cache": true,
	".mypy_cache":   true,
	"bin":           true,
	"obj":           true,
	".gradle":       true,
	".maven":        true,
	"site":          true,
	"template":      true,
	".samuel":       true,
}
